[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex']
hook_source = '''
    let g:latex_latexmk_options = '-pdfdvi'
    let g:latex_latexmk_continuous = 1
'''

[[plugins]]
repo = 'pdavydov108/vim-lsp-cquery'
on_ft = ['c', 'cpp', 'objc', 'objcpp', 'cc']

[[plugins]]
repo = 'ryanolsonx/vim-lsp-python'
on_ft = ['python']

[[plugins]]
repo = 'lighttiger2505/deoplete-vim-lsp'
on_source = ['vim-lsp-cquery', 'vim-lsp-python']

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'roxma/nvim-completion-manager'
on_ft = ['r']

[[plugins]]
repo = 'jalvesaq/Nvim-R'
on_ft = ['r']

[[plugins]]
repo = 'gaalcaras/ncm-R'
on_ft = ['r']
